"use server";
import { revalidatePath } from "next/cache";
import { TransactionType } from "@prisma/client";
import { prisma } from "@/lib/prisma";
import { financeRoles, requireRole } from "@/lib/permissions";
const text=(f:FormData,n:string)=>String(f.get(n)??"").trim();
export async function createFinancialYear(formData:FormData){const actor=await requireRole(...financeRoles);const enteredName=text(formData,"name");const digits=enteredName.replace(/\D/g,"");if(!/^\d{6}$/.test(digits))return;const name=`${digits.slice(0,4)}-${digits.slice(4)}`;const year=await prisma.financialYear.create({data:{name,startDate:new Date(text(formData,"startDate")),endDate:new Date(text(formData,"endDate")),openingBalance:text(formData,"openingBalance")||"0",isCurrent:formData.get("isCurrent")==="on"}});await prisma.auditLog.create({data:{userId:actor.id,action:"FINANCIAL_YEAR_CREATED",entityType:"FinancialYear",entityId:year.id,newData:{name:year.name,startDate:year.startDate.toISOString(),endDate:year.endDate.toISOString(),openingBalance:String(year.openingBalance),isCurrent:year.isCurrent}}});revalidatePath("/admin/finance");revalidatePath("/admin/activity")}
export async function createCategory(formData:FormData){const actor=await requireRole(...financeRoles);const name=text(formData,"name");const type=text(formData,"type") as TransactionType;const existing=await prisma.financialCategory.findUnique({where:{name}});const category=await prisma.financialCategory.upsert({where:{name},update:{type},create:{name,type}});await prisma.auditLog.create({data:{userId:actor.id,action:existing?"FINANCIAL_CATEGORY_UPDATED":"FINANCIAL_CATEGORY_CREATED",entityType:"FinancialCategory",entityId:category.id,oldData:existing?{name:existing.name,type:existing.type}:undefined,newData:{name:category.name,type:category.type}}});revalidatePath("/admin/finance");revalidatePath("/admin/activity")}
export async function createTransaction(formData:FormData){const user=await requireRole(...financeRoles);const amount=text(formData,"amount");if(!/^\d+(\.\d{1,2})?$/.test(amount))throw new Error("Enter a valid amount");const transaction=await prisma.financialTransaction.create({data:{financialYearId:text(formData,"financialYearId"),categoryId:text(formData,"categoryId"),eventId:text(formData,"eventId")||null,createdById:user.id,type:text(formData,"type") as TransactionType,date:new Date(text(formData,"date")),particulars:text(formData,"particulars"),amount,paymentMethod:text(formData,"paymentMethod")||null,referenceNumber:text(formData,"referenceNumber")||null,notes:text(formData,"notes")||null}});await prisma.auditLog.create({data:{userId:user.id,action:"FINANCIAL_TRANSACTION_CREATED",entityType:"FinancialTransaction",entityId:transaction.id,newData:{particulars:transaction.particulars,type:transaction.type,amount:String(transaction.amount),date:transaction.date.toISOString(),paymentMethod:transaction.paymentMethod,referenceNumber:transaction.referenceNumber}}});revalidatePath("/admin/finance");revalidatePath("/admin/activity")}
