import { prisma } from "@/lib/prisma";
import { requireAdmin } from "@/lib/auth";
import { AdminNavigateButton } from "@/components/admin-navigate-button";
import { Bell, CalendarDays, GraduationCap, Image, MessageSquare, Plus, Users } from "lucide-react";

export default async function AdminPage() {
  const profile = await requireAdmin();
  const [upcomingEvents, announcements, slideCount, userCount, teacherCount, feedbackCount, auditLogs] = await Promise.all([
    prisma.event.findMany({ where: { status: "UPCOMING" }, orderBy: { eventDate: "asc" }, take: 4 }),
    prisma.announcement.findMany({ where: { status: "PUBLISHED" }, orderBy: { publishedAt: "desc" }, take: 4 }),
    prisma.carouselSlide.count({ where: { status: "PUBLISHED" } }),
    prisma.userProfile.count({ where: { active: true, role: { in: ["ADMIN", "SUPER_ADMIN"] } } }),
    prisma.teacher.count({ where: { isPublished: true } }),
    prisma.feedback.count(),
    prisma.auditLog.findMany({ orderBy: { createdAt: "desc" }, take: 5, include: { user: true } }),
  ]);
  const metrics = [[CalendarDays,"Upcoming events",String(upcomingEvents.length),"Calendar entries"],[Bell,"Announcements",String(announcements.length),"Published updates"],[GraduationCap,"Teachers",String(teacherCount),"Published profiles"],[Image,"Carousel media",String(slideCount),"Live homepage slides"],[Users,"Active administrators",String(userCount),"Accounts with access"],[MessageSquare,"Feedback received",String(feedbackCount),"Community messages"]] as const;
  return <div className="adminDashboard">
    <section className="welcomeBanner"><div><p>GOOD MORNING</p><h1>{profile.fullName.split(" ")[0]}, your community is moving forward.</h1><span>{new Intl.DateTimeFormat("en-IN", { weekday: "long", day: "numeric", month: "long", year: "numeric" }).format(new Date())}</span></div><div className="welcomeGlow"><strong>Every action<br/>leaves a legacy.</strong></div></section>
    <section className="metricGrid" aria-label="Association metrics">{metrics.map(([Icon,label,value,detail])=><article className="metricCard" key={label}><div className="metricIcon"><Icon size={19}/></div><p>{label}</p><b>{value}</b><small>{detail}</small><span className="sparkline"><i/><i/><i/><i/><i/><i/></span></article>)}</section>
    <section className="actionRibbon"><div><p>QUICK ACTIONS</p><h2>Keep the momentum going.</h2></div><div>{[["/admin/events","Add event",CalendarDays],["/admin/announcements","New announcement",Bell],["/admin/teachers","Add teacher",GraduationCap],["/admin/carousel","Upload image",Image],["/admin/users","Manage access",Users]].map(([href,label,Icon])=>{const I=Icon as typeof Plus;return <AdminNavigateButton key={label as string} href={href as string} className="adminAction"><I size={16}/>{label as string}</AdminNavigateButton>})}</div></section>
    <section className="dashboardGrid"><article className="dashboardPanel"><div className="panelHeader"><div><p>UPCOMING</p><h2>Calendar</h2></div><AdminNavigateButton href="/admin/events">View all</AdminNavigateButton></div><div className="timelineList">{upcomingEvents.length?upcomingEvents.map(event=><AdminNavigateButton key={event.id} href="/admin/events" variant="ghost" className="eventLink"><time>{new Date(event.eventDate).toLocaleDateString("en-GB",{day:"2-digit",month:"short"})}</time><span><b>{event.title}</b><small>{event.venue??"Venue to be announced"}</small></span></AdminNavigateButton>):<div className="widgetEmpty"><CalendarDays size={20}/><span><b>No upcoming events</b><small>Create the next gathering from Events.</small></span></div>}</div></article><article className="dashboardPanel recentPanel"><div className="panelHeader"><div><p>ACTIVITY</p><h2>Recently changed</h2></div><AdminNavigateButton href="/admin/activity">View log</AdminNavigateButton></div><div className="activityList">{auditLogs.length?auditLogs.map(log=><div key={log.id}><span>{(log.user?.fullName??"A").slice(0,1)}</span><p><b>{log.user?.fullName??"Administrator"}</b> {log.action.toLowerCase().replaceAll("_"," ")}<small>{log.createdAt.toLocaleDateString("en-GB",{day:"2-digit",month:"short"})}</small></p></div>):<div className="widgetEmpty"><Bell size={20}/><span><b>Your activity will appear here</b><small>Changes are captured as the team works.</small></span></div>}</div></article><article className="dashboardPanel updatesPanel"><div className="panelHeader"><div><p>PUBLISHED</p><h2>Latest updates</h2></div><AdminNavigateButton href="/admin/announcements">Manage</AdminNavigateButton></div><div className="announcementList">{announcements.length?announcements.map(item=><AdminNavigateButton key={item.id} href="/admin/announcements" variant="ghost" className="updateLink"><span>{item.priority.slice(0,1)}</span><p><b>{item.title}</b><small>{item.body}</small></p></AdminNavigateButton>):<div className="widgetEmpty"><Bell size={20}/><span><b>No announcements published</b><small>Share a new update with your community.</small></span></div>}</div></article></section>
  </div>;
}
