"use client";

import { FormEvent, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { Eye, Filter, LoaderCircle, Plus, Search, ShieldCheck, UserCheck, UserRoundX, Users, X } from "lucide-react";
import { changeUserRole, createManagedUser, setUserActive } from "@/app/admin/users/actions";

export type UserRecord = { id: string; fullName: string; email: string; role: "USER" | "ADMIN" | "SUPER_ADMIN"; active: boolean; phone: string | null; batch: string | null; createdAt: string; updatedAt: string };
type UserRole = UserRecord["role"];

export function UsersWorkspace({ users, currentUserId, currentRole }: { users: UserRecord[]; currentUserId: string; currentRole: UserRole }) {
  const router = useRouter();
  const [query, setQuery] = useState("");
  const [role, setRole] = useState("ALL");
  const [selected, setSelected] = useState<UserRecord | null>(null);
  const [dialog, setDialog] = useState<"view" | "role" | "add" | null>(null);
  const [nextRole, setNextRole] = useState<UserRole>("USER");
  const [message, setMessage] = useState("");
  const [busy, setBusy] = useState(false);
  const filtered = useMemo(() => users.filter((user) => (role === "ALL" || user.role === role) && `${user.fullName} ${user.email}`.toLowerCase().includes(query.toLowerCase())), [users, query, role]);
  const superAdmins = users.filter((user) => user.role === "SUPER_ADMIN" && user.active).length;
  const open = (kind: "view" | "role", user: UserRecord) => { setSelected(user); setNextRole(user.role); setDialog(kind); setMessage(""); };
  const changeRole = async () => { if (!selected) return; setBusy(true); const data = new FormData(); data.set("userId", selected.id); data.set("role", nextRole); const result = await changeUserRole(data); setMessage(result.message); setBusy(false); if (result.ok) { setDialog(null); router.refresh(); } };
  const toggleActive = async (user: UserRecord) => { const verb = user.active ? "deactivate" : "reactivate"; if (!window.confirm(`${verb[0].toUpperCase() + verb.slice(1)} ${user.fullName}?`)) return; setBusy(true); const data = new FormData(); data.set("userId", user.id); data.set("active", String(!user.active)); const result = await setUserActive(data); setMessage(result.message); setBusy(false); if (result.ok) router.refresh(); };
  const addUser = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setBusy(true); const result = await createManagedUser(new FormData(event.currentTarget)); setMessage(result.message); setBusy(false); if (result.ok) { setDialog(null); router.refresh(); } };
  const roleOptions: UserRole[] = currentRole === "SUPER_ADMIN" ? ["USER", "ADMIN", "SUPER_ADMIN"] : ["USER", "ADMIN"];
  return <div className="usersWorkspace">
    <section className="usersHeader"><div><p className="adminKicker">ACCESS CONTROL</p><h1>User management</h1><span>Search accounts, govern access and review the three-level role hierarchy.</span></div>{currentRole === "SUPER_ADMIN" && <button className="addUserButton" type="button" onClick={() => { setDialog("add"); setSelected(null); setMessage(""); }}><Plus/>Add user</button>}</section>
    {message && <div className="userActionMessage" role="status">{message}</div>}
    <section className="userMetrics"><article><Users size={18}/><p>Total users</p><b>{users.length}</b></article><article><UserCheck size={18}/><p>Active users</p><b>{users.filter((user) => user.active).length}</b></article><article><ShieldCheck size={18}/><p>Super admins</p><b>{superAdmins}</b></article></section>
    <section className="usersPanel"><div className="usersToolbar"><div className="userSearch"><Search size={16}/><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search name or email" aria-label="Search users"/></div><div className="userFilters"><label><Filter size={15}/><select value={role} onChange={(event) => setRole(event.target.value)} aria-label="Filter by role"><option value="ALL">All roles</option><option value="USER">Users</option><option value="ADMIN">Admins</option><option value="SUPER_ADMIN">Super Admins</option></select></label></div></div>
      <div className="usersTable"><table><thead><tr><th>User</th><th>Role</th><th>Status</th><th>Created</th><th><span className="srOnly">Actions</span></th></tr></thead><tbody>{filtered.length ? filtered.map((user) => { const protectedUser = currentRole === "ADMIN" && user.role === "SUPER_ADMIN"; const self = currentUserId === user.id; return <tr key={user.id}><td><div className="userIdentity"><span>{user.fullName.slice(0,2).toUpperCase()}</span><div><b>{user.fullName}{self ? " (you)" : ""}</b><small>{user.email}</small></div></div></td><td><span className={`roleBadge role-${user.role.toLowerCase()}`}>{user.role.replaceAll("_", " ").toLowerCase()}</span></td><td><span className={user.active ? "activeBadge" : "inactiveBadge"}>{user.active ? "Active" : "Inactive"}</span></td><td>{new Date(user.createdAt).toLocaleDateString("en-GB",{day:"2-digit",month:"short",year:"numeric"})}</td><td><div className="userRowActions"><button type="button" onClick={() => open("view", user)} aria-label={`View ${user.fullName}`}><Eye/></button><button type="button" disabled={protectedUser || self} onClick={() => open("role", user)} aria-label={`Change ${user.fullName}'s role`}><ShieldCheck/></button><button type="button" disabled={protectedUser || self || (user.role === "SUPER_ADMIN" && superAdmins <= 1)} onClick={() => toggleActive(user)} aria-label={`${user.active ? "Deactivate" : "Reactivate"} ${user.fullName}`}><UserRoundX/></button></div></td></tr>; }) : <tr><td colSpan={5}><div className="usersEmpty"><Users size={25}/><b>No matching users</b><small>Try a different name or role filter.</small></div></td></tr>}</tbody></table></div>
    </section>
    <section className="permissionNotice"><ShieldCheck size={18}/><div><b>Role permissions are enforced by authenticated server actions and database policy.</b><span>Admins can manage User and Admin access. Only Super Admins can create accounts or manage the Super Admin role, and the final active Super Admin is protected.</span></div></section>
    {dialog && <div className="userDialogBackdrop" role="presentation" onMouseDown={(event) => { if (event.target === event.currentTarget) setDialog(null); }}><section className="userDialog" role="dialog" aria-modal="true" aria-labelledby="user-dialog-title"><header><div><p className="adminKicker">{dialog === "add" ? "SUPER ADMIN ACTION" : "USER ACCESS"}</p><h2 id="user-dialog-title">{dialog === "add" ? "Add user" : dialog === "role" ? "Change user role?" : "User profile"}</h2></div><button type="button" onClick={() => setDialog(null)} aria-label="Close dialog"><X/></button></header>
      {dialog === "view" && selected && <div className="userDetail"><span>{selected.fullName.slice(0,2).toUpperCase()}</span><h3>{selected.fullName}</h3><p>{selected.email}</p><dl><div><dt>Role</dt><dd>{selected.role.replaceAll("_"," ")}</dd></div><div><dt>Status</dt><dd>{selected.active ? "Active" : "Inactive"}</dd></div><div><dt>Phone</dt><dd>{selected.phone || "Not provided"}</dd></div><div><dt>Batch</dt><dd>{selected.batch || "Not provided"}</dd></div><div><dt>Created</dt><dd>{new Date(selected.createdAt).toLocaleDateString("en-GB",{dateStyle:"long"})}</dd></div></dl></div>}
      {dialog === "role" && selected && <div className="roleChange"><div className="roleTransition"><span><small>Current</small><b>{selected.role.replaceAll("_"," ")}</b></span><strong>→</strong><label><span>New role</span><select value={nextRole} onChange={(event) => setNextRole(event.target.value as UserRole)}>{roleOptions.map((item) => <option key={item} value={item}>{item.replaceAll("_"," ")}</option>)}</select></label></div><p className={selected.role === "SUPER_ADMIN" || nextRole === "SUPER_ADMIN" ? "strongWarning" : ""}>Changing this role will change the user&apos;s access to the administration system.{selected.role === "SUPER_ADMIN" || nextRole === "SUPER_ADMIN" ? " This is a privileged Super Admin change and will be recorded in the audit log." : ""}</p><div className="dialogActions"><button type="button" onClick={() => setDialog(null)}>Cancel</button><button type="button" disabled={busy || nextRole === selected.role} onClick={changeRole}>{busy && <LoaderCircle className="queueSpinner"/>}Confirm change</button></div></div>}
      {dialog === "add" && <form className="addUserForm" onSubmit={addUser}><label><span>Full name</span><input name="fullName" required minLength={2}/></label><label><span>Email</span><input name="email" type="email" required/></label><label><span>Temporary password <em>optional</em></span><input name="password" type="password" minLength={8} autoComplete="new-password"/><small>Leave blank to send a secure Supabase invitation instead.</small></label><div><label><span>Role</span><select name="role" defaultValue="USER"><option value="USER">User</option><option value="ADMIN">Admin</option><option value="SUPER_ADMIN">Super Admin</option></select></label><label><span>Phone <em>optional</em></span><input name="phone" type="tel"/></label><label><span>Batch <em>optional</em></span><input name="batch"/></label></div><p>Super Admin creation grants complete administrative access and is written to the audit log.</p><div className="dialogActions"><button type="button" onClick={() => setDialog(null)}>Cancel</button><button type="submit" disabled={busy}>{busy && <LoaderCircle className="queueSpinner"/>}Create user</button></div></form>}
      {message && <p className="dialogError" role="alert">{message}</p>}
    </section></div>}
  </div>;
}
